//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPBank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicRecord
    {
        public int AcademicRecordId { get; set; }
        public int PersonId { get; set; }
        public int EducationLevelListItemId { get; set; }
        public string InstituteName { get; set; }
        public Nullable<double> GPAObtained { get; set; }
        public Nullable<System.DateTime> CompletionYear { get; set; }
        public string Major { get; set; }
        public string Board { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
