//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPBank.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ListItemId { get; set; }
        public int ListItemCategoryId { get; set; }
        public string ListItemName { get; set; }
        public string ListItemDisplayName { get; set; }
    
        public virtual ListItemCategory ListItemCategory { get; set; }
    }
}
