//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPBank.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NPBankEntities : DbContext
    {
        public NPBankEntities()
            : base("name=NPBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicRecord> AcademicRecords { get; set; }
        public virtual DbSet<ListItem> ListItems { get; set; }
        public virtual DbSet<ListItemCategory> ListItemCategories { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
    }
}
